AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/IndentArray:
  IndentationWidth: 4

Layout/IndentHash:
  IndentationWidth: 4
